pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building project...'
                bat 'echo Compiling code'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                bat 'echo Running tests'
                bat 'exit 1'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
            }
        }
    }
}