pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                echo 'Cloning repository'
            }
        }

        stage('Build') {
            steps {
                dir('13th_Exp/calculator-maven') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('13th_Exp/calculator-maven') {
                    bat 'mvn test'
                }
            }
        }
    }

    post {
        always {
            junit '13th_Exp/calculator-maven/target/surefire-reports/*.xml'
        }
        success {
            echo 'All tests passed!'
        }
        failure {
            echo 'Some tests failed!'
        }
    }
}