pipeline {
    agent any

    stages {
        stage('Clone Code') {
            steps {
                echo 'Cloning repository'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('19th_Exp') {
                    sh 'docker build -t java-grade-app .'
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                sh 'docker stop java-grade-container || true'
                sh 'docker rm   java-grade-container || true'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -t --name java-grade-container java-grade-app'
            }
        }
    }
}
