pipeline {
    agent any

    environment {
        PROJECT_PATH = 'D:/BNMIT/6thSem/DevOps/Practice/13th_Exp/calculator-maven'
    }

    stages {
        stage('Build') {
            steps {
                dir("${env.PROJECT_PATH}") {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir("${env.PROJECT_PATH}") {
                    bat 'mvn test'
                }
            }
        }

        stage('Copy Reports') {
            steps {
                bat """
                if not exist "%WORKSPACE%\\reports" mkdir "%WORKSPACE%\\reports"
                xcopy /Y /E "${env.PROJECT_PATH}\\target\\surefire-reports" "%WORKSPACE%\\reports\\"
                """
            }
        }
    }

    post {
        always {
            junit 'reports/*.xml'
        }
    }
}